### ISSUE TITLE
Issue with Demo.py: AttributeError: module 'deduce' has no attribute 'lookup_lists'. Did you mean: 'lookup_sets'?

### ISSUE THREAD

**Issue by ahmb** [nedap/deidentify#70]
File "/usr/local/lib/python3.10/dist-packages/deidentify/taggers/__init__.py", line 1, in <module>
    from .deduce_tagger import DeduceTagger
  File "/usr/local/lib/python3.10/dist-packages/deidentify/taggers/deduce_tagger.py", line 4, in <module>
    from deidentify.methods.deduce import run_deduce
  File "/usr/local/lib/python3.10/dist-packages/deidentify/methods/deduce/run_deduce.py", line 14, in <module>
    NAME_PREFIX_REGEX = re.compile(r'({})\.?\s*'.format('|'.join(deduce.lookup_lists.PREFIXES)),
AttributeError: module 'deduce' has no attribute 'lookup_lists'. Did you mean: 'lookup_sets'?

**Comment by ahmb** [comment]
Name: deidentify
Version: 0.7.3

**Comment by ar2427** [comment]
Hi @jantrienes 

I faced a similar issue with the following traceback :

  Traceback (most recent call last):
    File "/Users/akhil/Downloads/touch.py", line 2, in <module>
      from deidentify.taggers import FlairTagger
    File "/opt/homebrew/lib/python3.10/site-packages/deidentify/taggers/__init__.py", line 1, in <module>
      from .deduce_tagger import DeduceTagger
    File "/opt/homebrew/lib/python3.10/site-packages/deidentify/taggers/deduce_tagger.py", line 4, in <module>
      from deidentify.methods.deduce import run_deduce
    File "/opt/homebrew/lib/python3.10/site-packages/deidentify/methods/deduce/run_deduce.py", line 14, in <module>
      NAME_PREFIX_REGEX = re.compile(r'({})\.?\s*'.format('|'.join(deduce.lookup_lists.PREFIXES)),
  AttributeError: module 'deduce' has no attribute 'lookup_lists'


The solution you suggested resolved the issue! Thanks!

**Comment by vempatisaivishal** [comment]
AttributeError: module 'deduce' has no attribute 'lookup_lists
I got the same issue can you please guide me how to resolve this issue
@ar2427 @jantrienes

**Comment by jantrienes** [comment]
Please refer to the comment above for a workaround 

> Could you please try a `pip install -U deduce>=1.0.2,<2` (see [#69](https://github.com/nedap/deidentify/pull/69)).

**Comment by vempatisaivishal** [comment]
I tried the same thing in Google colab but still I am getting the same issue
is it the problem of the Google colab
@jantrienes any other suggestions from your side

**Comment by marijnvanwingerden** [comment]
> I tried the same thing in Google colab but still I am getting the same issue is it the problem of the Google colab [@jantrienes](https://github.com/jantrienes) any other suggestions from your side

Dear Vishal, we indeed found that deidentify did not run on a certain Colab instance. But it runs locally, however not on the latest python versions
